### ISSUE TITLE
Connector for clickhouse

### ISSUE THREAD

**Issue by benfdking** [quarylabs/quary#212]
### Please Describe The Problem To Be Solved

<img width="1242" alt="image" src="https://github.com/quarylabs/quary/assets/9087625/714b868b-d882-4538-9216-ff4ab708b80d">

### Optional: Suggest A Solution

Implement a connector for click house.

**Comment by Slach** [comment]
nice proposal, hope will it implements soon

**Comment by benfdking** [comment]
This has been implemented, but it's not quite everywhere yet but it does work and is documented here: https://www.quary.dev/docs/configuration#clickhouse

**Comment by Slach** [comment]
@benfdking thank you so much for your efforts Ben

**Comment by benfdking** [comment]
Let me know how it goes! If there are any problems, please raise.
