### ISSUE TITLE
[BUG] error: failed to load manifest for workspace member `/usr/ports/misc/quary/quary/proto/gen/rust`

### ISSUE THREAD

**Issue by yurivict** [quarylabs/quary#233]
### Current Behavior:
```
[yuri@yv /usr/ports/misc/quary/quary]$ cargo build
error: failed to load manifest for workspace member `/usr/ports/misc/quary/quary/proto/gen/rust`
referenced by workspace at `/usr/ports/misc/quary/quary/Cargo.toml`

Caused by:
  failed to read `/usr/ports/misc/quary/quary/proto/gen/rust/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

This file is missing: proto/gen/rust/Cargo.toml

### Environment:

Example:
- OS: FreeBSD 14.0

**Comment by louisjoecodes** [comment]
Hello! We have a Makefile at the root of the repository with some of the commands that you'll need to compile Quary - it looks like you're missing some Proto-related setup.

Try running: 
make proto
make rust_build

**Comment by yurivict** [comment]
This solved the problem.

Thank you!
