### ISSUE TITLE
Created views are not materialized views

### ISSUE THREAD

**Issue by kraftaa** [quarylabs/quary#24]
I ran `quary build` and got a result as a `view` in `postgres` but it's not a `materialized view`.  I checked `quary/rust/core/src/database_postgres` and it has
```
 fn automatic_cache_sql_create_statement(
        &self,
        model: &str,
        model_cache_name: &str,
    ) -> Vec<String> {
        vec![format!(
            "CREATE OR REPLACE VIEW {} AS SELECT * FROM {}",
```
in `dbt`   I can add `materialized: materialized_view` to `dbt_project.yml` but don't see such an option in `quary`.
Which config I need to change to get a materialized view. 
Thank you

**Comment by kraftaa** [comment]
I found in https://github.com/quarylabs/quary/blob/b6b46581ba9da79be4f12f97b1585af14276af82/rust/core/src/databases.rs#L7 that the only supported materialization is `view`. Is it possible to add `materialized_view`? 
thank you

**Comment by benfdking** [comment]
Hi @kraftaa,

Thanks for getting the feedback to us. We default to `View` but have built the infrastructure to enable different materializations. Let me just finish the materialized view for Postgres and get that out for you.

**Comment by benfdking** [comment]
Hi @kraftaa, that should now be with you in the latest build (0.0.101) and the one you can pull through `brew`. This is how you would invoke it in your project files. 

```yaml
models:
  - name: test_model_out
    materialization: table
  - name: test_model_same_schema
    materialization: materialized_view
```

I hope that helps, and let us know if you have any other feedback! We appreciate it.

**Comment by kraftaa** [comment]
@benfdking thank you! I didn't see your answer yesterday and just forked this repo and added changes (`CREATE/DROP` for materialized views and tables in `rust/core/src/databases` ) - didn't see them in the code, and it works like magic with `schema.yaml` with the models. I'm working on Mac, but my program will be running in kube in ubuntu pod. 
(I've just checked with `brew` it does work, thank you!)

I have a question: when we create a view/table we better do `CREATE OR REPLACE` or `CREATE/DROP` but in the case of materialized views shouldn't we do `REFRESH MATERIALIZED VIEW name` instead of completely recreating it? 
I'm looking at the code, looks like it will require adding a new command in `rust/cli/src/commands.rs` .

thank you!

**Comment by benfdking** [comment]
Ok, a few bits and bobs in here: 

**Running on kube** 

You'll have to install the binary in your image to run on Kubernetes. At the moment, we build an `x86` Linux build, which I assume should do the trick. If you need an `arm` build, let us know. You can download the built binaries from our releases: https://github.com/quarylabs/quary/releases and use them. 

Or, if you give us the day, we can get prebuilt docker images built for you which might be easier to do.

**Refreshing materialized view**

Let me get back to you on that one with some more concrete thoughts.

**Comment by benfdking** [comment]
Just updated the above with some thoughts.

**Comment by kraftaa** [comment]
@benfdking thank you. yes I see the build for `x86` which works for us, though we are running some stuff at `arm` too, if you can push `arm` build in the future, it'll be great. I rebuilt it for myself before seeing yesterday changes, but there is no need for it now :) 
I'm trying to tweak commands/core in order to make `cargo run refresh` work, but probably I will stick with the current version.

PS: we are really excited to see "dbt" in Rust, Python is too slow for that. thank you!
