### ISSUE TITLE
[Question] Is this replacement Cube.js?

### ISSUE THREAD

**Issue by dfdgsdfg** [quarylabs/quary#272]
Hello!

This product looks very promising! 😊

Is it a replacement for https://cube.dev/?

**Comment by benfdking** [comment]
Hey @dfdgsdfg 

Thanks for reaching out. One of our tasks is to draw a small comparison chart of the competitive landscape. 

There's some overlap, of course, with Cube.JS as you would expect in the BI/analytics space. At a general level: 

- Both of our tools provide a level of modelling (but ours is quite different) 
- Both tools are written in Rust
- Both tools are open-source 

The differences are probably more revealing: 

- Our focus is very much BI applications where as Cube has a much wider reach in terms of application/caching/api that Quary does not tackle
- Cube modeling is based on a semantic layer where we have focused on SQL transformations
  - Cube "models" requires queries to be directed through a Cube server
  - Quary "models" can be just pushed back to the database for other applications
- Quary can just run client side which Cube doesn't quite do in the same way. 

Some differences and hopefully revealing.
