### ISSUE TITLE
Two nit issues in the model chart view

### ISSUE THREAD

**Issue by benfdking** [quarylabs/quary#273]
Two nit issues 

nit: If no asset is selected block the Play button
![image](https://github.com/quarylabs/quary/assets/9087625/d1882ec8-5e38-4b6b-85bf-9b4d128c3d9b)

nit: could improve error message
![image](https://github.com/quarylabs/quary/assets/9087625/e853aab1-dcbd-4077-93d4-881ddbe034d0)

_Originally posted by @benfdking in https://github.com/quarylabs/quary/issues/270#issuecomment-2126592416_

**Comment by louisjoecodes** [comment]
resolved both
