### ISSUE TITLE
Are there plans to support cross-data source query analysis?

### ISSUE THREAD

**Issue by wking1986** [quarylabs/quary#408]
I have two data sources, one in snowflake and the other in postgresql. 
Can quary support cross-data source query analysis?

**Comment by benfdking** [comment]
We don't quite yet have any plans to support this out of the box. You can achieve some of this behaviour with DuckDB which you can use to query other sources.

**Comment by wking1986** [comment]
Got it！Thank you for your reply

**Comment by benfdking** [comment]
I am going to close this issue, do let us know if you have any other questions around this matter.
