### ISSUE TITLE
[BUG] error[E0412]: cannot find type `PanicHookInfo` in module `panic`

### ISSUE THREAD

**Issue by yurivict** [quarylabs/quary#492]
Build fails with rust-nightly-1.80.0.20240507:

```
error[E0412]: cannot find type `PanicHookInfo` in module `panic`
   --> /wrkdirs/usr/ports/misc/quary/work/sqruff-fbebef96dbaa0adf01ca3140e212d78168c007b8/crates/lib/src/helpers.rs:154:46
    |
154 |         let hook = move |panic_info: &panic::PanicHookInfo<'_>| {
    |                                              ^^^^^^^^^^^^^ help: a struct with a similar name exists: `PanicInfo`
    |
   ::: /usr/local/lib/rustlib/src/rust/library/core/src/panic/panic_info.rs:26:1
    |
26  | pub struct PanicInfo<'a> {
    | ------------------------ similarly named struct `PanicInfo` defined here

```

### Environment:

- Version: 0.4.3
- OS: FreeBSD 14.1

### Anything else

The field panic::PanicHookInfo isn't in the [documentation](https://doc.rust-lang.org/std/panic/index.html).
Where is it available?

**Comment by gvozdvmozgu** [comment]
`PanicInfo` is considered deprecated as of version 1.82.0. It seems like you need to update your compiler version.

https://doc.rust-lang.org/nightly/std/panic/type.PanicInfo.html
https://doc.rust-lang.org/nightly/std/panic/struct.PanicHookInfo.html

**Comment by yurivict** [comment]
> PanicInfo is considered deprecated as of version 1.82.0. It seems like you need to update your compiler version.


Why does then [this line](https://github.com/quarylabs/quary/blob/main/Cargo.lock#L4516) pins sqruff to the version that uses PanicInfo

Does quary still require rust-nightly?

**Comment by gvozdvmozgu** [comment]
Sqruff has not used `PanicInfo` since version 0.10. Currently, both Sqruff and Quary use the version specified in `rust-toolchain.toml`, which is `nightly-2024-07-22`.

```bash
quary> cat .\rust-toolchain.toml
[toolchain]
channel = "nightly-2024-07-22"
quary> cargo -V
cargo 1.82.0-nightly (5f6b9a922 2024-07-19)
```

You're using Rust version 1.80, which indeed doesn't have `PanicHookInfo` as it was introduced in version 1.81.0.

**Comment by yurivict** [comment]
I'll wait for 1.82.0 to be available.
Thanks!

**Comment by gvozdvmozgu** [comment]
Perhaps we should consider releasing binary files for FreeBSD?

**Comment by yurivict** [comment]
Binaries aren't usable for ports - we rebuild everything from source.
